{
 "title": "Test-Cluster-TiDB-Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "description": "TiDB uptime since the last restart.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{job=\"tidb\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "description": "TiDB current connection counts.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "tidb_server_connections", "legendFormat": "{{instance}}" },
      { "expr": "sum(tidb_server_connections)", "legendFormat": "total" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "TiDB CPU usage calculated with process CPU running seconds.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"tidb\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "TiDB process rss memory usage.\nTiDB heap memory size in use.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"tidb\"}",
       "legendFormat": "process-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"tidb\"}",
       "legendFormat": "heap-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "TiDB query durations by histogram buckets with different percents.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket{sql_type!=\"internal\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket{sql_type!=\"internal\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "sum(rate(tidb_server_handle_query_duration_seconds_sum{sql_type!=\"internal\"}[30s])) / sum(rate(tidb_server_handle_query_duration_seconds_count{sql_type!=\"internal\"}[30s]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Failed Query OPS",
     "type": "graph",
     "description": "TiDB failed query statistics by query type.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_server_execute_error_total[1m])) by (type, instance)",
       "legendFormat": " {{type}}-{{instance}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "description": "TiDB query processing numbers per second.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_query_total[1m])) by (result)",
       "legendFormat": "query {{result}}"
      }
     ]
    },
    {
     "title": "QPS By Instance",
     "type": "graph",
     "description": "TiDB query total statistics including both successful and failed ones.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(tidb_server_query_total[1m])",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "QPS by Statement",
     "type": "graph",
     "description": "TiDB statement statistics by statement type.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_executor_statement_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "QPS by CMD",
     "type": "graph",
     "description": "MySQL command statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(tidb_server_query_total[1m])",
       "legendFormat": " {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parse Duration",
     "type": "graph",
     "description": "The time cost of parsing SQL to AST",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_parse_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_parse_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "95"
      }
     ]
    },
    {
     "title": "Compile Duration",
     "type": "graph",
     "description": "The time cost of building the query plan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_compile_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_compile_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "95"
      }
     ]
    },
    {
     "title": "Execution Duration",
     "type": "graph",
     "description": "The time cost of executing the SQL which does not include the time to get the results of the query .",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_execute_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_execute_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "95"
      }
     ]
    },
    {
     "title": "Queries Using Plan Cache OPS",
     "type": "graph",
     "description": "TiDB plan cache hit total.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_plan_cache_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS",
     "type": "graph",
     "description": "TiDB transaction processing counts by type.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_session_transaction_duration_seconds_count{sql_type=\"general\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Bucketed histogram of transaction execution durations, including retry.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_transaction_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "Max Transaction Statement Num",
     "type": "graph",
     "description": "The max TiDB statements numbers within one transaction.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_session_transaction_statement_num_bucket{sql_type=\"general\"}[30s])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "Max Transaction Retry Num",
     "type": "graph",
     "description": "The max TiDB transaction retry count.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(tidb_session_retry_num_bucket[30s])) by (le))",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Slow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Request Duration 99 by store",
     "type": "graph",
     "description": "KV request durations by store (TiKV). It contains requests that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le, store))",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "KV Request Duration 99 by type",
     "type": "graph",
     "description": "KV request durations by request type. It contains requests that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le,type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Request OPS",
     "type": "graph",
     "description": "KV request count by request type. It contains requests that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_txn_cmd_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Transaction OPS",
     "type": "graph",
     "description": "TiDB total kv transaction counts. It contains transactions that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_txn_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max Transaction Write Size Bytes",
     "type": "graph",
     "description": "The max writes bytes of the transaction. It contains transactions that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_size_bytes_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max Transaction Write KV Num",
     "type": "graph",
     "description": "The max writes kv count of the transaction. It contains transactions that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_kv_num_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max Transaction Regions Num",
     "type": "graph",
     "description": "The max writes regions of the transaction. It contains transactions that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_regions_num_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "PD TSO Wait Duration",
     "type": "graph",
     "description": "The duration of TiDB starts to wait for the TSO until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "PD TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client starting to wait for the TS until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "AutoID QPS",
     "type": "graph",
     "description": "TiDB auto-ID requests per second including single table/global auto-ID processing and single table auto-ID rebase processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_autoid_operation_duration_seconds_count[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AutoID Duration",
     "type": "graph",
     "description": "TiDB auto-ID requests durations.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_autoid_operation_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "sum(rate(tidb_autoid_operation_duration_seconds_sum[1m])) / sum(rate(tidb_autoid_operation_duration_seconds_count[1m]))",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  }
 ]
}